CREATE TABLE Nodes_Low_voltage_DATA (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DATA_DATE DATE NOT NULL,
    nodes VARCHAR2(250 BYTE) not null,
    season_antecedent VARCHAR2(250 BYTE),
    description_constraints VARCHAR2(250 BYTE)
)